apiVersion: v1
kind: Pod
metadata:
  name: example-pod
  labels:
    app: example-app
spec:
  containers:
  - name: example-ct
    # image: nginx:stable
    image: gmlwlswldbs/test:latest
    ports:
    - containerPort: 80
  imagePullSecrets:
  - name: docker-secret

---
apiVersion: v1
kind: Service
metadata:
  name: example-svc
spec:
  selector:
    app: example-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
