apiVersion: apps/v1         
kind: Deployment
metadata:
  namespace: default 
  name: test_1
  labels:
    app: test_1
spec:
  replicas: 1 
  minReadySeconds: 10
  selector:
    matchLabels:
      app: test_1
  template: 
    metadata:
      labels: 
        app: test_1
    spec:
      nodeSelector:
        zone: private
        role: worker
      containers:
      - name: test_1
        image: gmlwlswldbs/test:latest
        imagePullPolicy: Always
        resources:        
            requests:
              memory: "1Gi"
              cpu: "200m"
            limits:
              memory: "1Gi"
              cpu: "500m"
      imagePullSecrets:
      - name: docker-secret
---
apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: test_1
  labels:
    app: test_1
spec:
  selector:
    app: test_1
  type: ClusterIP
  ports:
  - port: 8080

