version: '3.0'

services:
    runner:
        image: ubuntu:20.04
        build:
            context: .
        ports:
          - "80:80"
        expose:
          - "80"
        command:
          - |
            /mkdir actions-runner
            /cd actions-runner
            /curl -o actions-runner-linux-x64-2.312.0.tar.gz -L https://github.com/actions/runner/releases/download/v2.312.0/actions-runner-linux-x64-2.312.0.tar.gz
            /echo "85c1bbd104d539f666a89edef70a18db2596df374a1b51670f2af1578ecbe031  actions-runner-linux-x64-2.312.0.tar.gz" | shasum -a 256 -c# Extract the installer
            /tar xzf ./actions-runner-linux-x64-2.312.0.tar.gz
            /./config.sh --url https://github.com/KimJY37/github-action-test --token ATV4XUA6BOSOTRJ47GBDZYTFYQ76Q
            /./run.sh
