name: test-1
run-name: ${{ github.actor }} is learning GitHub Actions
on: push
jobs:
  check-bats-version:
    runs-on: self-hosted
    steps:
      - name: Npm Install, build and test
        run: |
          npm ci
          npm run build
          npm test
