name: test-1
run-name: ${{ github.actor }} is learning GitHub Actions
on: push
jobs:
  Install:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: npm install
        run: npm install
  Deploy:
    runs-on: self-hosted
    steps:
      - name: deploy
        run: docker run Dockerfile
      
      
      
      
          
